# Generated by Django 6.0.6 on 2026-06-22 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('submitter_name', models.CharField(max_length=100)),
                ('submitter_email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('finance', 'Finance'), ('operations', 'Operations'), ('technology', 'Technology'), ('hr', 'Human Resources'), ('sales', 'Sales & Marketing'), ('legal', 'Legal & Compliance'), ('other', 'Other')], default='technology', max_length=50)),
                ('business_sponsor', models.CharField(blank=True, max_length=100)),
                ('problem_statement', models.TextField(blank=True)),
                ('expected_benefits', models.TextField(blank=True)),
                ('proposed_solution', models.TextField(blank=True)),
                ('strategic_alignment', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_duration_months', models.IntegerField(blank=True, null=True)),
                ('target_go_live', models.DateField(blank=True, null=True)),
                ('dependencies', models.TextField(blank=True)),
                ('constraints', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('intake', 'Intake'), ('triage', 'Triage & Deduplication'), ('research', 'Research & Enrichment'), ('brief', 'Project Brief'), ('business_case', 'Business Case'), ('scoring', 'Scoring & Prioritisation'), ('prc', 'PRC Decision'), ('backlog', 'Approved Backlog'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('duplicate', 'Duplicate')], default='intake', max_length=20)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small  (<$50K)'), ('medium', 'Medium ($50K–$500K)'), ('large', 'Large  (>$500K)')], max_length=10)),
                ('ai_processing', models.BooleanField(default=False)),
                ('awaiting_decision', models.BooleanField(default=False)),
                ('triage_output', models.JSONField(blank=True, null=True)),
                ('research_output', models.JSONField(blank=True, null=True)),
                ('project_brief', models.JSONField(blank=True, null=True)),
                ('business_case', models.JSONField(blank=True, null=True)),
                ('scoring_output', models.JSONField(blank=True, null=True)),
                ('prc_pack', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='tpmo.initiative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate', models.CharField(choices=[('triage', 'Triage Gate'), ('brief_review', 'Brief Review Gate'), ('bc_review', 'Business Case Review Gate'), ('scoring_review', 'Scoring Review Gate'), ('prc', 'PRC Decision Gate')], max_length=30)),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('defer', 'Defer'), ('request_info', 'Request More Information'), ('escalate', 'Escalate')], max_length=20)),
                ('decided_by_name', models.CharField(blank=True, max_length=100)),
                ('rationale', models.TextField()),
                ('conditions', models.TextField(blank=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='tpmo.initiative')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Initiative Submitted'), ('stage_advanced', 'Stage Advanced'), ('agent_triggered', 'Agent Triggered'), ('agent_completed', 'Agent Completed'), ('decision_recorded', 'Decision Recorded'), ('artefact_updated', 'Artefact Updated'), ('status_changed', 'Status Changed')], max_length=30)),
                ('actor', models.CharField(max_length=100)),
                ('from_stage', models.CharField(blank=True, max_length=20)),
                ('to_stage', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tpmo.initiative')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentOutput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('agent_role', models.CharField(max_length=150)),
                ('task_name', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=20)),
                ('input_summary', models.TextField(blank=True)),
                ('raw_output', models.TextField(blank=True)),
                ('structured_output', models.JSONField(blank=True, null=True)),
                ('is_mock', models.BooleanField(default=False)),
                ('execution_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_outputs', to='tpmo.initiative')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_alignment', models.IntegerField(default=0)),
                ('business_value', models.IntegerField(default=0)),
                ('urgency', models.IntegerField(default=0)),
                ('risk_inverse', models.IntegerField(default=0)),
                ('feasibility', models.IntegerField(default=0)),
                ('complexity_inverse', models.IntegerField(default=0)),
                ('resource_availability', models.IntegerField(default=0)),
                ('roi_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payback_months', models.IntegerField(blank=True, null=True)),
                ('npv', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ps_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sas_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('composite_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('priority_rank', models.IntegerField(blank=True, null=True)),
                ('ai_recommendation', models.TextField(blank=True)),
                ('scoring_rationale', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(auto_now=True)),
                ('initiative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='tpmo.initiative')),
            ],
        ),
    ]
